### PR TITLE
Update for KDE Plasma 6 and Qt6

### PR DESCRIPTION
**Pull request by jhrldev**
This depends on Tofee/qmltermwidget@1e7ab36e9894f9d7c5b7d82267faba1e60efd635, which has PR open on upstream: Swordfish90/qmltermwidget#41.

`jq` is a dependency for building because [KDE Plasma 6](https://develop.kde.org/docs/plasma/widget/porting_kf6/#porting-an-existing-plasmoid) changed its metadata format to json.

`X-KDE-PluginInfo-KdeStoreId` was I removed because `desktoptojson` complained that it didn't know about this property, although it still work with the property regardless.

If you want to try building it, clone [this branch of qmltermwidget](https://github.com/Tofee/qmltermwidget/tree/tofe/qt6) and follow the regular instructions for building, but replace `qmake` with `qmake6`:

```bash
$ git clone -b tofe/qt6 https://github.com/Tofee/qmltermwidget/
$ cd qmltermwidget
$ qmake6 && make
$ sudo make install
```
Then build my changes, install and run:

```bash
$ plasmawindowed com.koldbyte.kde.termoid
```

### CODE REVIEW

**Comment by Yixuan2020** [comment]
i got the updated version to build on Fedora40 but the general section looks broken 
image

**Comment by dhay3** [comment]
> i got the updated version to build on Fedora40 but the general section looks broken image
> 
> and i get
> 
> ```
> qt.gui.imageio: libpng warning: iCCP: CRC error
> qt.gui.imageio: libpng warning: iCCP: CRC error
> qt.gui.imageio: libpng warning: iCCP: CRC error
> qt.gui.imageio: libpng warning: iCCP: CRC error
> ```
> 
> not sure if this is a problem on my side



> i got the updated version to build on Fedora40 but the general section looks broken image
> 
> and i get
> 
> ```
> qt.gui.imageio: libpng warning: iCCP: CRC error
> qt.gui.imageio: libpng warning: iCCP: CRC error
> qt.gui.imageio: libpng warning: iCCP: CRC error
> qt.gui.imageio: libpng warning: iCCP: CRC error
> ```
> 
> not sure if this is a problem on my side

@Yixuan2020 the properties of  SpinBox has been changed in Qt6, I will do a patch base on @JonathanxD 's PR.

**Comment by Yixuan2020** [comment]
i also tired to update it but couldn't figure the spinbox out

**Comment by dhay3** [comment]
> i also tired to update it but couldn't figure the spinbox out

You could try my PR [dhay3/termoid](https://github.com/dhay3/termoid/tree/plasma6).

**Comment by JonathanxD** [comment]
I didn't notice that the configuration was broken, I still use it daily but never had to change the configuration.

@dhay3 thanks for the patch, I'll try it out and merge into my branch if it works.

**Comment by dri3sp** [comment]
Thank you, this works!

**Comment by YamiYukiSenpai** [comment]
Safe to say this is abandoned.  Might as well fork it and call it "termoid6" or soemthing

**Comment by JonathanxD** [comment]
> Safe to say this is abandoned. Might as well fork it and call it "termoid6" or soemthing

Sadly. And the [upstream patch needed](https://github.com/Swordfish90/qmltermwidget/pull/41) was never merged as well.

Unfortunately, I have no desire to maintain a fork of Termoid, there are some bugs and missing features that I would love to implement, but I don't feel like doing it anytime soon (if ever, but who knows).

The only thing I can say is that I'll be probably updating this PR for as long as I keep using Termoid.

**Comment by koldbyte** [comment]
Apologies for being inactive. 
Unfortunately, I am currently unable to provide ample time to add new fixes or feature but I will definitely accept community support. I will try taking out some time to test PRs and ensure this doesn't get abandoned.

Thanks @JonathanxD for your support.   +1
I can merge this PR this weekend and update the new releases. Let me know if you have any other changes you want to add.

**Comment by JonathanxD** [comment]
@koldbyte No worries. I have no new changes to push, feel free to merge it as it is.

**Comment by YamiYukiSenpai** [comment]
> Sadly. And the [upstream patch needed](https://github.com/Swordfish90/qmltermwidget/pull/41) was never merged as well.

https://github.com/Swordfish90/qmltermwidget/pull/41#issuecomment-2557121269
guy just replied 2 weeks ago LOL

**Pull request merged**
